### ISSUE TITLE
Error: signature does not match event payload and secret

### ISSUE THREAD

**Issue by kuldeepkeshwar** [chadfawcett/probot-serverless-now#11]
I am getting `Error: signature does not match event payload and secret` on webhook invocation.

I have pushed  .env(which has app id & webhook secret) &  .pem file(which has the private key) to now.sh.  

Although the same setup from local machine is working fine.

I have even tried with multiple private keys too.

<img width="763" alt="Screen Shot 2019-07-01 at 2 25 52 PM" src="https://user-images.githubusercontent.com/10448534/60423608-31c44e00-9c0c-11e9-92cb-1d45a2102877.png">

**Comment by chadfawcett** [comment]
Hi @kuldeepkeshwar the environment variables will need to be passed to `now` either through the deploy command, or through the `now.json` config file. [See docs for reference](https://zeit.co/docs/v2/deployments/environment-variables-and-secrets/)

The `now.json` file should include an `env` section like so:
```json
{
  "env": {
    "APP_ID": "app-id",
    "WEBHOOK_SECRET": "my-secret"
  }
}
```

In order to keep your secrets and private keys secure, you'll likely want to add them to now as `secrets`. `now secret add my-secret my-secret-value-abc123` then you can reference the secrets like `@my-secret`.
```json
{
  "env": {
    "APP_ID": "app-id",
    "WEBHOOK_SECRET": "@my-secret"
  }
}
```

If that doesn't work, can you provide your `now.json` file as well as any relevant logs that `now` might be outputting?

**Comment by kuldeepkeshwar** [comment]
@chadfawcett I already have secrets(app-id,webhook-secret,private-key) setup on now. and now.json is configured in the way as you mentioned, but sometimes it works & sometimes it doesn't, not sure why this is happening. 
Can using the same private from multiple locations(local machine & now.sh) cause this?

**Comment by chadfawcett** [comment]
Hmm I don't think that would be caused by using the same private key in multiple places. When you say sometimes it works and sometimes it doesn't, are you referring to your original statement that it works locally but not on now? Or does it sometimes work and sometimes not work on now?

What logs are being output from your now lambda?

**Comment by kuldeepkeshwar** [comment]
> When you say sometimes it works and sometimes it doesn't, are you referring to your original statement that it works locally but not on now? Or does it sometimes work and sometimes not work on now?

👆both ways.

In logs, I was getting
`Error: signature does not match event payload and secret`. I guess This is a typical error you get when the checksum fails.  

If I update the webhook secret, will private key still be valid🤔? (shooting arrows in the dark) 🙃

**Comment by chadfawcett** [comment]
@kuldeepkeshwar Were you able to resolve this? Was wondering what ended up being the solution incase someone else runs into this issue in the future.

**Comment by kuldeepkeshwar** [comment]
@chadfawcett, I am not sure why it was happening, I ended up deleting the bot and re-created it. 
My guess is if you change bot's setting after generating the private key. I couldn't find anything that says how the signature is validated and what role does the private key play.
