### ISSUE TITLE
Should multiple apps be supported?

### ISSUE THREAD

**Issue by chadfawcett** [chadfawcett/probot-serverless-now#6]
The better approach is to deploy multiple apps separately, however apps like the [sentry](https://github.com/probot/probot/blob/master/src/apps/sentry.ts) which override the logger would need to be installed on the same instance. Apps like [stats](https://github.com/probot/probot/blob/master/src/apps/stats.ts) could be deployed separately, but are pretty small in size that they might not need to be.

Arguably I think the Sentry functionality could be implemented using the [extensions](https://probot.github.io/docs/extensions/) approach rather than it being a separate app. If this is in fact possible, I'd rather keep this package only accepting a single app and publish a separate package that implements the Sentry functionality as an extension.

**Comment by tcbyrd** [comment]
> Arguably I think the Sentry functionality could be implemented using the extensions approach rather than it being a separate app.

One thing we've talked about is Probot should probably implement is an official way to add middleware. I believe the reason we implemented Sentry as an app is to ensure all errors are reported for the entire app, as opposed to only reported inside a specific module (`appFn`). As an extension, you'd have to load Sentry separately for each module. This part is a little different though with `@now/node`, since each path can be an entirely different process reporting to its own Sentry DSN.

Also just a heads up that the `stats` app doesn't scale well in serverless environments since it has to paginate through all installations to determine popularity. After a couple dozen installations, we typically recommend disabling it on ephemeral deployment environments like Now and Glitch. We even disable it on our big production apps that have thousands of installations for similar reasons.

The pattern I think makes the most sense here is one module (or `appFn`) per deployment and Sentry can be optionally started as part of something like `probot.run()`. This `run` method needs to be implemented to support custom startup options like this, but that's a TODO I want to try and get implemented before we ship the next version of Probot.

**Comment by chadfawcett** [comment]
Thanks for the comment @tcbyrd!

I didn't dig into how the logging was implemented, so I just went based off of a guess on how the Sentry app worked. My thought was that it's just adding or replacing the logger on the `app` instance `https://github.com/probot/probot/blob/bb06c51485245d75508982826180e7c2e774a7db/src/apps/sentry.ts#L14`
https://github.com/probot/probot/blob/bb06c51485245d75508982826180e7c2e774a7db/src/apps/sentry.ts#L14

If this is the case, wouldn't you be able to set the `app.log.target` in any module (appFn) that is being loaded? As you mention, for `@now/node` this is a bit different, so you would likely need it loaded into each module regardless, no?

I opened https://github.com/probot/probot/issues/794 after some discussion with @JasonEtco on Slack. This seems to fit in with the `probot.run()` if I'm not mistaken. Let me know if I can help with that.

**Comment by tcbyrd** [comment]
> As you mention, for @now/node this is a bit different, so you would likely need it loaded into each module regardless, no?

If each handler only loads one module, yes. But there is a concept of being able to take an array of modules (`appFn[]`) for one Probot app (`app`), so it's not out of the question that you could have one handler function that loads the Sentry module and other modules at the same time.

> I opened probot/probot#794 after some discussion with @JasonEtco on Slack. 

👍 Must have missed that while I was out for the holidays. I feel like once we have programmatic start implemented, we can re-factor the `serverless-*` extensions to use that, so they end up being just an easier way to implement that provider's handler signature.
